# Generated by Django 5.1.2 on 2024-10-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='max_incorrect_guesses',
        ),
    ]
